name: dart_z80
description: Zilog Z80 microprocessor emulator core. Designed for use as part of a 8-bit computer system emulator.
version: 0.1.0
repository: https://github.com/timsneath/z80

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
